# Generated by Django 5.0 on 2025-09-20 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skills', models.TextField(help_text='List required skills, separated by commas')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary in USD', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_or_on_site', models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On-site'), ('hybrid', 'Hybrid')], default='on_site', max_length=10)),
                ('visa_sponsorship', models.CharField(choices=[('yes', 'Visa Sponsorship Available'), ('no', 'No Visa Sponsorship')], default='no', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
