# Generated by Django 5.2.7 on 2025-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_education_workexperience_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public (anyone can view)'), ('recruiters', 'Recruiters only'), ('private', 'Private (only me)')], default='public', help_text='Who can see your profile.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email_to_recruiters',
            field=models.BooleanField(default=False, help_text='If on, recruiters can see your email on your profile page.'),
        ),
    ]
