# Generated by Django 5.2.4 on 2025-10-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_education_workexperience_profile_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commute_radius",
            field=models.PositiveIntegerField(
                default=50, help_text="Preferred commute radius in kilometers"
            ),
        ),
    ]
