# Generated by Django 5.2.7 on 2025-10-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_privacy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public (anyone can view)'), ('recruiters', 'Recruiters only')], default='public', help_text='Who can see your profile.', max_length=20),
        ),
    ]
