# Generated by Django 5.2.7 on 2025-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_privacy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public (anyone can view)'), ('private', 'Private (only me)')], default='public', help_text='Public: Recruiters can view your profile and find you in search. Private: Recruiters cannot view your profile; you won’t appear in candidate search.', max_length=20),
        ),
    ]
