# Generated by Django 5.0 on 2025-10-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_conversation_message'),
        ('accounts', '0008_alter_profile_privacy_level'),
    ]

    operations = [
    ]
