# Generated by Django 5.2.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_merge_20251026_1649"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedCandidateSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name for this search (e.g., 'Python Developers in NYC')",
                        max_length=200,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("project_keyword", models.CharField(blank=True, max_length=200)),
                (
                    "match_all_skills",
                    models.BooleanField(
                        default=True,
                        help_text="If True, candidates must have all selected skills (AND). If False, any selected skill (OR).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If active, recruiter will be notified of new matches",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True,
                        help_text="When we last checked for new matches",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchMatchNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_match_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.savedcandidatesearch",
                    ),
                ),
            ],
            options={
                "ordering": ["-notified_at"],
                "unique_together": {("saved_search", "candidate")},
            },
        ),
        migrations.AddField(
            model_name="savedcandidatesearch",
            name="skills",
            field=models.ManyToManyField(blank=True, to="accounts.skill"),
        ),
    ]

