# Generated by Django 5.0 on 2025-11-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_savedcandidatesearch_searchmatchnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for location mapping', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for location mapping', max_digits=9, null=True),
        ),
    ]
